### ISSUE TITLE
Printed output

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstimate#10]
The current output from remstimate starts with:

```
Relational Event Model (tie oriented) 

Call:
some ~ formula + here + as + to + the + linear + predictor


Coefficients (MLE with interval likelihood):
```

The line "some ~ formula + here + as + to + the + linear + predictor" should be replaced with the actual formula. This is useful.

**Comment by jupepis** [comment]
If the input of statistics:
- is a `remstats` object, then the output will be the formula defined in `remstats`.
- is an array provided by the user, then the printed output won't have any formula (yet to be integrated).
