### ISSUE TITLE
Allow user-computed statistics in remstimate

### ISSUE THREAD

**Issue by reck0ner** [TilburgNetworkGroup/remstimate#11]
When the input `stats` is not a `remstats` object, but it is an array provided by the user, the columns of such array must be re-ordered according to the new order of actors/dyads defined from the `reh` object. 
The reordering should be carried out by `remstimate::remstimate()`.

The user should provide a list of arrays/array like the remstats' one but with columns named according to the name of actors/dyads in the original edgelist.

Column names are crucial to make the reordering happen.

**Comment by jupepis** [comment]
I close this issue because about an old version of `remstimate`. The current version of `remstimate` works only with `remstats` objects.
