### ISSUE TITLE
argument `model` is redundant

### ISSUE THREAD

**Issue by SNAnalyst** [TilburgNetworkGroup/remstimate#18]
The `model` argument is redundant, since `remstimate` now requires a `reh` object which itself already includes the `model` argument: `attr(rehObject, "model")`.

Besides, allowing the user to specify this argument might lead to a user specifying another model than the one used for the calculation of the statistics, which should be prevented.

I suggest to remove the `model` argument from `remstimate` and get its value internally from the `reh` object.

**Comment by jupepis** [comment]
`model` is not anymore an input argument of the function `remstimate::remstimate()`. It is now processed internally from the input `reh` object.
