### ISSUE TITLE
error in computing p values & post probs?

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remstimate#28]
For an effect I got this result in the summary:

```
                Estimate    Std. Err     z value Pr(>|z|) Pr(=0)
itp1         -2.0685e+01  7.4310e+05 -2.7836e-05   1.0000 0.9914
```

Based on the Z value the p value should be 0 and the post prob of the null should be 0 as well, right?!

**Comment by jupepis** [comment]
I see that the standard error is very large, so this result may be due to this. I could only check the calculation of the p-value which is correct.  As to the posterior probability (Pr(=0)) I would need the degrees of freedom of the null model, which are the number of events in the sequence.

**Comment by jomulder** [comment]
Sorry Giuseppe. I totally looked at it wrongly...

**Comment by jupepis** [comment]
I close this issue as solved
